'use strict';

const PriorityQueue = require('../lib/priority-queue');

describe('tests for priority-queue.js', () => {
  test('testing that enqueue behaves properly and priority-queue stores highest priority objects in internal array at index 0, also testing that peek returns the highest priority queue in the heap', () => {
    let testQueue = new PriorityQueue();
    expect(testQueue.peek()).toBeNull();
    testQueue.enqueue({priority: 5, value: 'a'});
    expect(testQueue.peek()).toEqual('a');
    testQueue.enqueue({priority: 2, value: 'b'});
    expect(testQueue.peek()).toEqual('b');
    testQueue.enqueue({priority: 6, value: 'c'});
    expect(testQueue.peek()).toEqual('b');
  });

  test('testing that enqueue stores objects with the same priority in the queue order - FIFO', () => {
    let testQueue = new PriorityQueue();
    expect(testQueue.peek()).toBeNull();
    testQueue.enqueue({priority: 2, value: 'a'});
    testQueue.enqueue({priority: 2, value: 'b'});
    expect(testQueue.peek()).toEqual('a');
    testQueue.enqueue({priority: 6, value: 'c'});
    expect(testQueue.peek()).toEqual('a');
    testQueue.enqueue({priority: 1, value: 'd'});
    expect(testQueue.peek()).toEqual('d');
  });

  test('testing that dequeue method properly returns highest priority value in the priority-queue and removes that value', () => {
    let testQueue = new PriorityQueue();
    testQueue.enqueue({priority: 2, value: 'a'});
    expect(testQueue.dequeue()).toEqual('a');
    expect(testQueue.dequeue()).toBeNull();
    testQueue.enqueue({priority: 5, value: 'f'});
    testQueue.enqueue({priority: 3, value: 'd'});
    testQueue.enqueue({priority: 1, value: 'a'});
    testQueue.enqueue({priority: 2, value: 'b'});
    testQueue.enqueue({priority: 2, value: 'c'});
    testQueue.enqueue({priority: 3, value: 'e'});
    expect(testQueue.dequeue()).toEqual('a');
    expect(testQueue.dequeue()).toEqual('b');
    expect(testQueue.dequeue()).toEqual('c');
    expect(testQueue.dequeue()).toEqual('d');
    expect(testQueue.dequeue()).toEqual('e');
    expect(testQueue.dequeue()).toEqual('f');
  });

  test('testing that dequeue method properly returns highest priority value in the priority-queue and removes that value in edge cases', () => {
    let testQueue = new PriorityQueue();
    testQueue.enqueue({priority: 1, value: 'a'});
    testQueue.enqueue({priority: 2, value: 'b'});
    testQueue.enqueue({priority: 3, value: 'e'});
    testQueue.enqueue({priority: 3, value: 'f'});
    testQueue.enqueue({priority: 2, value: 'c'});
    testQueue.enqueue({priority: 4, value: 'h'});
    testQueue.enqueue({priority: 5, value: 'i'});
    testQueue.enqueue({priority: 6, value: 'j'});
    testQueue.enqueue({priority: 7, value: 'k'});
    testQueue.enqueue({priority: 3, value: 'g'});
    testQueue.enqueue({priority: 8, value: 'l'});
    testQueue.enqueue({priority: 2, value: 'd'});
    expect(testQueue.dequeue()).toEqual('a');
    expect(testQueue.dequeue()).toEqual('b');
    expect(testQueue.dequeue()).toEqual('c');
    expect(testQueue.dequeue()).toEqual('d');
    expect(testQueue.dequeue()).toEqual('e');
    expect(testQueue.dequeue()).toEqual('f');
    expect(testQueue.dequeue()).toEqual('g');
    expect(testQueue.dequeue()).toEqual('h');
    expect(testQueue.dequeue()).toEqual('i');
    expect(testQueue.dequeue()).toEqual('j');
    expect(testQueue.dequeue()).toEqual('k');
    expect(testQueue.dequeue()).toEqual('l');
  });

  test('testing that FIFO is preserved when priority is constant/in order', () => {
    let testQueue = new PriorityQueue();
    testQueue.enqueue({priority: 1, value: 'a'});
    console.log(testQueue._data);
    testQueue.enqueue({priority: 1, value: 'b'});
    console.log(testQueue._data);
    testQueue.enqueue({priority: 1, value: 'c'});
    console.log(testQueue._data);
    testQueue.enqueue({priority: 1, value: 'd'});
    console.log(testQueue._data);
    testQueue.enqueue({priority: 1, value: 'e'});
    console.log(testQueue._data);
    testQueue.enqueue({priority: 1, value: 'f'});
    console.log(testQueue._data);
    testQueue.enqueue({priority: 2, value: 'g'});
    console.log(testQueue._data);
    testQueue.enqueue({priority: 3, value: 'h'});
    console.log(testQueue._data);
    testQueue.enqueue({priority: 3, value: 'i'});
    console.log(testQueue._data);
    testQueue.enqueue({priority: 3, value: 'j'});
    console.log(testQueue._data);
    testQueue.enqueue({priority: 3, value: 'k'});
    console.log(testQueue._data);
    testQueue.enqueue({priority: 4, value: 'l'});
    console.log(testQueue._data);
    testQueue.enqueue({priority: 4, value: 'm'});
    console.log(testQueue._data);
    expect(testQueue.dequeue()).toEqual('a');
    console.log(testQueue._data);
    expect(testQueue.dequeue()).toEqual('b');
    console.log(testQueue._data);
    expect(testQueue.dequeue()).toEqual('c');
    console.log(testQueue._data);
    expect(testQueue.dequeue()).toEqual('d');
    console.log(testQueue._data);
    expect(testQueue.dequeue()).toEqual('e');
    console.log(testQueue._data);
    expect(testQueue.dequeue()).toEqual('f');
    console.log(testQueue._data);
    expect(testQueue.dequeue()).toEqual('g');
    console.log(testQueue._data);
    expect(testQueue.dequeue()).toEqual('h');
    console.log(testQueue._data);
    expect(testQueue.dequeue()).toEqual('i');
    console.log(testQueue._data);
    expect(testQueue.dequeue()).toEqual('j');
    console.log(testQueue._data);
    expect(testQueue.dequeue()).toEqual('k');
    console.log(testQueue._data);
    expect(testQueue.dequeue()).toEqual('l');
    console.log(testQueue._data);
    expect(testQueue.dequeue()).toEqual('m');
  });
});